### ISSUE TITLE
opencv version

### ISSUE THREAD

**Issue by itismycode** [Be997398715/EAO-SLAM-Final#1]
A great job!!! when I install this project, i meet some problem about version of opencv and libvkt. Are OpenCV 4.5.1 is used here?

**Comment by Be997398715** [comment]
Yes,  OpenCV==4.5.x is ok.

**Comment by itismycode** [comment]
Thank you for your reply. By the way, what are the versions of VTK and PCL

**Comment by itismycode** [comment]
> Thank you for your reply. By the way, what are the versions of VTK and PCL

vtk 7.1.1 && pcl1.8.1 are OK!!
